/**
 * Texts of the exported workpaper, in Portuguese and English. Values that formulas compare with
 * (origins, yes/no, statuses) come from here too, so the formulas and the data always use the same words.
 */
import type { SignalId } from '../../config/schema';

export type Language = 'pt' | 'en';

const pt = {
  sheets: {
    summary: 'Resumo',
    deletionJust: 'Justificativa da Exclusao',
    changeJust: 'Justificativa da Alteração',
    documents: 'Documentos',
    lines: 'Base_Linhas',
    deletions: 'Exclusoes',
    changes: 'Alteracoes',
    unbalanced: 'Desbalanceados',
    discardedDetail: 'Alteracoes_Descartadas_Detalhe',
    discardedSummary: 'Alteracoes_Descartadas_Resumo',
    criteria: 'Criterios',
    trace: 'Rastreabilidade',
    helper: 'Auxiliar',
  },
  values: {
    manual: 'Manual',
    automatic: 'Automático',
    mixed: 'Misto',
    unidentified: 'Não identificado',
    yes: 'Sim',
    no: 'Não',
    notEvaluable: 'Não avaliável',
    complete: 'Completa',
    partial: 'Parcial',
    total: 'Total',
    deleted: 'Excluído',
    active: 'Vigente',
    pending: 'Pendente',
    justified: 'Justificado',
    moved: 'Movimentado após a justificativa',
    corrected: 'Corrigido',
    accounting: 'Contábil',
    complement: 'Complemento',
    undefined: 'Indefinido',
    none: '—',
    emptyUser: '(sem usuário no log)',
    custom: 'Personalizado',
    fullLog: 'Log completo',
    file: 'Arquivo',
    activation: 'Efetivação do tipo de saldo',
    stamp: 'Somente carimbo de usuário',
    effective: 'Alteração efetiva',
    discarded: 'Descartado',
    considered: 'Considerado',
    pendingNote: 'Justificativa pendente',
    movedNote: 'Movimentado depois da justificativa: revise o texto e confirme na coluna ao lado.',
    action: 'Ação',
    info: 'Informativo',
    ok: 'OK',
    weekdays: ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sáb'],
  },
  nature: { '1': 'Débito', '2': 'Crédito', '3': 'Débito e Crédito', '4': 'Complemento de histórico' } as Record<string, string>,
  operations: { insert: 'Inclusão', update: 'Alteração', delete: 'Exclusão', restore: 'Recuperação' },
  categories: { deleted: 'Excluído', changed: 'Alterado', unbalanced: 'Desbalanceado', posted: 'Postado' },
  cols: {
    key: 'Documento',
    recno: 'Recno',
    origin: 'Origem',
    nature: 'Natureza',
    lineType: 'Tipo de linha',
    value: 'Valor (R$)',
    debit: 'Débito (R$)',
    credit: 'Crédito (R$)',
    status: 'Situação',
    accountingLines: 'Linhas contábeis',
    complementLines: 'Linhas de complemento',
    deletedLines: 'Linhas excluídas',
    changedLines: 'Linhas alteradas',
    lines: 'Linhas',
    debitRecorded: 'Débito registrado (R$)',
    creditRecorded: 'Crédito registrado (R$)',
    diffRecorded: 'Diferença registrada (R$)',
    debitCurrent: 'Débito vigente (R$)',
    creditCurrent: 'Crédito vigente (R$)',
    diffCurrent: 'Diferença vigente (R$)',
    base: 'Base de avaliação',
    excluded: 'Excluído',
    unbalanced: 'Desbalanceado',
    firstDeletion: 'Data/hora da 1ª exclusão',
    lastDeletion: 'Data/hora da última exclusão',
    lastChange: 'Última alteração efetiva — {file}',
    firstPosting: 'Data/hora da 1ª postagem',
    deletionJust: 'Justificativa da exclusão',
    deletionStatus: 'Situação da justificativa da exclusão',
    changeJust: 'Justificativa da alteração',
    changeStatus: 'Situação da justificativa da alteração',
    deletedInPeriod: 'Excluído no período aplicado',
    changedInPeriod: 'Alterado no período aplicado',
    pendingInPeriod: 'Pendente no período aplicado',
    insertUser: 'Usuário da inclusão',
    insertTime: 'Data/hora da inclusão',
    deleteUser: 'Usuário da exclusão',
    deleteTime: 'Data/hora da exclusão',
    changes: 'Alterações efetivas',
    inconsistency: 'Inconsistência',
    docUnbalanced: 'Documento desbalanceado',
    files: 'Arquivos',
    file: 'Arquivo',
    time: 'Data/hora',
    user: 'Usuário',
    field: 'Campo',
    fieldLabel: 'Descrição do campo',
    oldValue: 'Valor anterior',
    newValue: 'Valor atualizado',
    lineValue: 'Valor da linha (R$)',
    currentStatus: 'Situação atual',
    kind: 'Tipo de movimento',
    events: 'Eventos',
    records: 'Registros',
    responsible: 'Responsável',
    note: 'Observação',
    confirmNew: 'Abrange o novo evento?',
    movementFiles: 'Arquivos com movimento',
    lastEvent: 'Último evento',
    coveredFiles: 'Arquivos cobertos',
    lastCovered: 'Último evento coberto',
    movedAtExport: 'Movimentado após a justificativa (na exportação)',
    docDiffRecorded: 'Diferença registrada do documento (R$)',
    docDiffCurrent: 'Diferença vigente do documento (R$)',
  },
  summary: {
    title: 'Log de auditoria CFGR700 — tabela {table} — papel de trabalho',
    subtitle: 'Escopo: {scope} · Arquivos: {files} · Eventos de {first} a {last}',
    generated: 'Gerado em {when} pelo AuditAnalyzer (versão {version}). Os arquivos foram processados no computador do usuário.',
    okBanner: 'Todas as verificações bloqueantes passaram (ver Rastreabilidade).',
    failBanner: 'ATENÇÃO: exportado com {n} verificação(ões) bloqueante(s) com falha, confirmadas pelo usuário: {list}.',
    filter: 'FILTRO — todos os quadros respondem ao período escolhido aqui',
    period: 'Período (atalho)',
    customStart: 'Início personalizado',
    customEnd: 'Fim personalizado',
    cutoff: 'Data de corte (competência)',
    appliedStart: 'Início aplicado',
    appliedEnd: 'Fim aplicado',
    days: 'Dias no período',
    help: 'Campos em amarelo são editáveis. Para um período livre, escolha "Personalizado" e informe as datas. O filtro usa a data do evento (inclusão, alteração ou exclusão), não a data contábil.',
    s1: '1. Categorias por origem — período aplicado',
    s1cols: ['Categoria', 'Manual — lançamentos', 'Manual — documentos', 'Manual — valor debitado (R$)', 'Automático — lançamentos', 'Automático — documentos', 'Automático — valor debitado (R$)', 'Documentos mistos', 'Total de documentos', 'Não identificados — lançamentos'],
    s1note: 'Documentos são contados no período do primeiro evento (1ª exclusão, 1ª postagem); alterações, pela data de cada arquivo. Não identificados = registros sem origem no log (lançados antes do início do log e só alterados).',
    s2: '2. Período aplicado × demais dias × log completo',
    s2cols: ['Categoria', 'Período — lançamentos', 'Período — documentos', 'Período — valor (R$)', 'Demais dias — lançamentos', 'Demais dias — documentos', 'Demais dias — valor (R$)', 'Log completo — lançamentos', 'Log completo — documentos', 'Log completo — valor (R$)'],
    s3: '3. Composição por data contábil — período aplicado',
    s3cols: ['Categoria', 'Até o corte — lançamentos', 'Até o corte — documentos', 'Até o corte — valor (R$)', 'Após o corte — lançamentos', 'Após o corte — documentos', 'Após o corte — valor (R$)', 'Data contábil ilegível — lançamentos', 'Data contábil ilegível — documentos', 'Sem identificação — lançamentos'],
    s3note: 'O log registra a data do evento; a data contábil (CT2_DATA) pode ser anterior ou posterior. A soma das colunas é igual ao total das categorias.',
    s4: '4. Sinalizações — período aplicado',
    s4cols: ['Verificação', 'Ocorrências', 'Situação', 'Exige ação'],
    s4note: 'Dias úteis = segunda a sexta, exceto os feriados da aba Auxiliar. A lista dos dias está no movimento diário (quadro 7).',
    s5: '5. Cobertura das justificativas — período aplicado',
    s5cols: ['Categoria', 'Documentos no período', 'Justificados', 'Movimentados após a justificativa', 'Pendentes', 'Cobertura'],
    s5rows: ['Documentos excluídos', 'Documentos alterados'],
    s5note: 'Preencha as justificativas nas abas de justificativa: as situações e a cobertura se atualizam sozinhas. "Movimentado após a justificativa" (calculado na exportação) exige confirmar se o texto abrange o novo evento.',
    s6: '6. Critério de corte das alterações (eventos por extração)',
    s6cols: ['Tipo de movimento', 'Tratamento'],
    s6total: 'Total de eventos de alteração',
    s7: '7. Movimento diário',
    s7cols: ['Data', 'Dia', 'Postados', 'Excluídos', 'Alterados', 'Eventos', 'No período', 'Dia útil', 'Coberto por extração'],
    s8: '8. Onde conferir',
    where: {
      deletionJust: 'Motivo de cada documento excluído; células vazias em amarelo.',
      changeJust: 'Motivo de cada documento alterado; células vazias em amarelo.',
      documents: 'Um documento contábil por linha: totais, situação, datas e justificativas.',
      lines: 'Um registro de CT2 por linha: valores, situação, inclusão, exclusão e alterações.',
      deletions: 'Cada lançamento excluído, com usuário e data/hora.',
      changes: 'Cada campo alterado em alterações efetivas.',
      unbalanced: 'Linhas dos documentos com débito diferente de crédito.',
      discardedDetail: 'Eventos de alteração descartados pelo critério de corte (efetivação e carimbo).',
      discardedSummary: 'Eventos descartados por tipo, arquivo e usuário.',
      criteria: 'Premissas, definições e limitações.',
      trace: 'Arquivos, SHA-256, reconciliação, verificações e configuração usadas.',
      helper: 'Parâmetros do filtro, atalhos, feriados e movimento diário que alimentam o Resumo.',
    },
  },
  helper: {
    title: 'Parâmetros e tabelas auxiliares do Resumo',
    param: 'Parâmetro',
    value: 'Valor',
    appliedStart: 'Início aplicado',
    appliedEnd: 'Fim aplicado',
    cutoff: 'Data de corte aplicada',
    logFirst: 'Primeiro dia com evento',
    logLast: 'Último dia com evento',
    presets: 'Atalhos de período',
    presetCols: ['Atalho', 'Início', 'Fim'],
    holidays: 'Feriados',
    daily: 'Movimento diário',
  },
  trace: {
    title: 'Rastreabilidade',
    tool: 'Ferramenta',
    version: 'Versão (commit)',
    generated: 'Gerado em',
    language: 'Idioma',
    scope: 'Escopo exportado',
    configHash: 'SHA-256 da configuração',
    cutoff: 'Data de corte usada',
    holidays: 'Feriados',
    presets: 'Atalhos do usuário',
    files: 'Arquivos',
    fileCols: ['Arquivo', 'Tamanho (bytes)', 'SHA-256', 'Primeiro evento', 'Último evento', 'Linhas da planilha', 'Após o 1º cabeçalho', 'Cabeçalhos repetidos', 'Linhas em branco', 'Linhas de detalhe', 'Reconciliação', 'Inclusão', 'Alteração', 'Exclusão', 'Recuperação', 'Total de eventos', 'Entradas do ZIP conferidas'],
    params: 'Parâmetros do relatório',
    paramCols: ['Arquivo', 'Pergunta', 'Parâmetro', 'Valor'],
    checks: 'Verificações',
    checkCols: ['Verificação', 'Nível', 'Resultado', 'Detalhe'],
    blocking: 'Bloqueante',
    warning: 'Alerta',
    passed: 'OK',
    failed: 'Falha',
    confirmed: 'Exportação confirmada pelo usuário com falhas bloqueantes em {when}.',
    justifications: 'Justificativas',
    justCols: ['Tipo', 'Documentos', 'Justificados', 'Movimentados após a justificativa', 'Pendentes'],
    coverageNote: 'A cobertura de cada justificativa (arquivos e último evento cobertos) está nas abas de justificativa; importar esta planilha na ferramenta recupera a cobertura exata.',
  },
  criteria: {
    title: 'Critérios, premissas e limitações',
  },
  kinds: { deletion: 'Exclusão', change: 'Alteração' },
  file: 'Papel de trabalho CFGR700 - {scope} - {date}.xlsx',
  consolidated: 'Consolidado',
  daysListNote: '(ver o movimento diário)',
};

type Labels = typeof pt;

const en: Labels = {
  sheets: {
    summary: 'Summary',
    deletionJust: 'Deletion justifications',
    changeJust: 'Change justifications',
    documents: 'Documents',
    lines: 'Lines',
    deletions: 'Deletions',
    changes: 'Changes',
    unbalanced: 'Unbalanced',
    discardedDetail: 'Discarded_changes_detail',
    discardedSummary: 'Discarded_changes_summary',
    criteria: 'Criteria',
    trace: 'Traceability',
    helper: 'Helper',
  },
  values: {
    manual: 'Manual',
    automatic: 'Automatic',
    mixed: 'Mixed',
    unidentified: 'Unidentified',
    yes: 'Yes',
    no: 'No',
    notEvaluable: 'Not evaluable',
    complete: 'Complete',
    partial: 'Partial',
    total: 'Total',
    deleted: 'Deleted',
    active: 'Active',
    pending: 'Pending',
    justified: 'Justified',
    moved: 'Moved after the justification',
    corrected: 'Corrected',
    accounting: 'Accounting',
    complement: 'Complement',
    undefined: 'Undefined',
    none: '—',
    emptyUser: '(no user in the log)',
    custom: 'Custom',
    fullLog: 'Full log',
    file: 'File',
    activation: 'Balance-type activation',
    stamp: 'User stamp only',
    effective: 'Effective change',
    discarded: 'Discarded',
    considered: 'Considered',
    pendingNote: 'Justification pending',
    movedNote: 'Moved after the justification: review the text and confirm in the column beside.',
    action: 'Action',
    info: 'Information',
    ok: 'OK',
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  nature: { '1': 'Debit', '2': 'Credit', '3': 'Debit and credit', '4': 'History complement' },
  operations: { insert: 'Insert', update: 'Update', delete: 'Delete', restore: 'Restore' },
  categories: { deleted: 'Deleted', changed: 'Changed', unbalanced: 'Unbalanced', posted: 'Posted' },
  cols: {
    key: 'Document',
    recno: 'Recno',
    origin: 'Origin',
    nature: 'Nature',
    lineType: 'Line type',
    value: 'Amount',
    debit: 'Debit',
    credit: 'Credit',
    status: 'Status',
    accountingLines: 'Accounting lines',
    complementLines: 'Complement lines',
    deletedLines: 'Deleted lines',
    changedLines: 'Changed lines',
    lines: 'Lines',
    debitRecorded: 'Recorded debit',
    creditRecorded: 'Recorded credit',
    diffRecorded: 'Recorded difference',
    debitCurrent: 'Current debit',
    creditCurrent: 'Current credit',
    diffCurrent: 'Current difference',
    base: 'Evaluation basis',
    excluded: 'Deleted',
    unbalanced: 'Unbalanced',
    firstDeletion: 'First deletion',
    lastDeletion: 'Last deletion',
    lastChange: 'Last effective change — {file}',
    firstPosting: 'First posting',
    deletionJust: 'Deletion justification',
    deletionStatus: 'Deletion justification status',
    changeJust: 'Change justification',
    changeStatus: 'Change justification status',
    deletedInPeriod: 'Deleted in the applied period',
    changedInPeriod: 'Changed in the applied period',
    pendingInPeriod: 'Pending in the applied period',
    insertUser: 'Insert user',
    insertTime: 'Insert time',
    deleteUser: 'Delete user',
    deleteTime: 'Delete time',
    changes: 'Effective changes',
    inconsistency: 'Inconsistency',
    docUnbalanced: 'Unbalanced document',
    files: 'Files',
    file: 'File',
    time: 'Time',
    user: 'User',
    field: 'Field',
    fieldLabel: 'Field description',
    oldValue: 'Old value',
    newValue: 'New value',
    lineValue: 'Line amount',
    currentStatus: 'Current status',
    kind: 'Movement type',
    events: 'Events',
    records: 'Records',
    responsible: 'Responsible',
    note: 'Note',
    confirmNew: 'Covers the new event?',
    movementFiles: 'Files with movement',
    lastEvent: 'Last event',
    coveredFiles: 'Files covered',
    lastCovered: 'Last event covered',
    movedAtExport: 'Moved after the justification (at export)',
    docDiffRecorded: 'Document recorded difference',
    docDiffCurrent: 'Document current difference',
  },
  summary: {
    title: 'CFGR700 audit log — table {table} — workpaper',
    subtitle: 'Scope: {scope} · Files: {files} · Events from {first} to {last}',
    generated: 'Generated on {when} by AuditAnalyzer (version {version}). The files were processed on the user\'s computer.',
    okBanner: 'All blocking checks passed (see Traceability).',
    failBanner: 'WARNING: exported with {n} failing blocking check(s), confirmed by the user: {list}.',
    filter: 'FILTER — every table below follows the period chosen here',
    period: 'Period (preset)',
    customStart: 'Custom start',
    customEnd: 'Custom end',
    cutoff: 'Cutoff date (accrual)',
    appliedStart: 'Applied start',
    appliedEnd: 'Applied end',
    days: 'Days in the period',
    help: 'Yellow cells are editable. For a free period, choose "Custom" and type the dates. The filter uses the event date (insert, change or deletion), not the accounting date.',
    s1: '1. Categories by origin — applied period',
    s1cols: ['Category', 'Manual — lines', 'Manual — documents', 'Manual — debited amount', 'Automatic — lines', 'Automatic — documents', 'Automatic — debited amount', 'Mixed documents', 'Total documents', 'Unidentified — lines'],
    s1note: 'Documents are counted in the period of their first event (first deletion, first posting); changes, by the date of each file. Unidentified = records without origin in the log (posted before the log started and only changed).',
    s2: '2. Applied period × other days × full log',
    s2cols: ['Category', 'Period — lines', 'Period — documents', 'Period — amount', 'Other days — lines', 'Other days — documents', 'Other days — amount', 'Full log — lines', 'Full log — documents', 'Full log — amount'],
    s3: '3. Composition by accounting date — applied period',
    s3cols: ['Category', 'Up to cutoff — lines', 'Up to cutoff — documents', 'Up to cutoff — amount', 'After cutoff — lines', 'After cutoff — documents', 'After cutoff — amount', 'Unreadable accounting date — lines', 'Unreadable accounting date — documents', 'Unidentified — lines'],
    s3note: 'The log records the event date; the accounting date (CT2_DATA) may be earlier or later. The columns add up to the category totals.',
    s4: '4. Signals — applied period',
    s4cols: ['Check', 'Occurrences', 'Status', 'Requires action'],
    s4note: 'Business days = Monday to Friday, except the holidays in the Helper sheet. The list of days is in the daily movement (table 7).',
    s5: '5. Justification coverage — applied period',
    s5cols: ['Category', 'Documents in the period', 'Justified', 'Moved after the justification', 'Pending', 'Coverage'],
    s5rows: ['Deleted documents', 'Changed documents'],
    s5note: 'Fill in the justifications in the justification sheets: statuses and coverage update automatically. "Moved after the justification" (computed at export) requires confirming whether the text covers the new event.',
    s6: '6. Change cut-off criterion (events per extraction)',
    s6cols: ['Movement type', 'Treatment'],
    s6total: 'Total change events',
    s7: '7. Daily movement',
    s7cols: ['Date', 'Day', 'Posted', 'Deleted', 'Changed', 'Events', 'In the period', 'Business day', 'Covered by an extraction'],
    s8: '8. Where to check',
    where: {
      deletionJust: 'Reason for each deleted document; empty cells in yellow.',
      changeJust: 'Reason for each changed document; empty cells in yellow.',
      documents: 'One accounting document per row: totals, status, dates and justifications.',
      lines: 'One CT2 record per row: amounts, status, insert, deletion and changes.',
      deletions: 'Each deleted line, with user and time.',
      changes: 'Each field changed in effective changes.',
      unbalanced: 'Lines of the documents whose debit differs from credit.',
      discardedDetail: 'Change events discarded by the cut-off criterion (activation and stamp).',
      discardedSummary: 'Discarded events by type, file and user.',
      criteria: 'Assumptions, definitions and limitations.',
      trace: 'Files, SHA-256, reconciliation, checks and configuration used.',
      helper: 'Filter parameters, presets, holidays and daily movement behind the Summary.',
    },
  },
  helper: {
    title: 'Parameters and helper tables of the Summary',
    param: 'Parameter',
    value: 'Value',
    appliedStart: 'Applied start',
    appliedEnd: 'Applied end',
    cutoff: 'Applied cutoff date',
    logFirst: 'First day with events',
    logLast: 'Last day with events',
    presets: 'Period presets',
    presetCols: ['Preset', 'Start', 'End'],
    holidays: 'Holidays',
    daily: 'Daily movement',
  },
  trace: {
    title: 'Traceability',
    tool: 'Tool',
    version: 'Version (commit)',
    generated: 'Generated on',
    language: 'Language',
    scope: 'Exported scope',
    configHash: 'Configuration SHA-256',
    cutoff: 'Cutoff date used',
    holidays: 'Holidays',
    presets: 'User presets',
    files: 'Files',
    fileCols: ['File', 'Size (bytes)', 'SHA-256', 'First event', 'Last event', 'Sheet rows', 'After first header', 'Repeated headers', 'Blank rows', 'Detail rows', 'Reconciliation', 'Insert', 'Update', 'Delete', 'Restore', 'Total events', 'ZIP entries checked'],
    params: 'Report parameters',
    paramCols: ['File', 'Question', 'Parameter', 'Value'],
    checks: 'Checks',
    checkCols: ['Check', 'Level', 'Result', 'Detail'],
    blocking: 'Blocking',
    warning: 'Warning',
    passed: 'OK',
    failed: 'Failed',
    confirmed: 'Export confirmed by the user with failing blocking checks on {when}.',
    justifications: 'Justifications',
    justCols: ['Kind', 'Documents', 'Justified', 'Moved after the justification', 'Pending'],
    coverageNote: 'The coverage of each justification (files and last event covered) is in the justification sheets; importing this workbook into the tool restores the exact coverage.',
  },
  criteria: {
    title: 'Criteria, assumptions and limitations',
  },
  kinds: { deletion: 'Deletion', change: 'Change' },
  file: 'CFGR700 workpaper - {scope} - {date}.xlsx',
  consolidated: 'Consolidated',
  daysListNote: '(see the daily movement)',
};

export const LABELS: Record<Language, Labels> = { pt, en };
export type { Labels };

/** English texts for the signals (the configuration holds the Portuguese ones). */
export const SIGNALS_EN: Record<SignalId, { label: string; text: string; none: string }> = {
  unbalancedDocuments: { label: 'Unbalanced documents', text: '{n} unbalanced document(s)', none: 'No unbalanced document' },
  unjustifiedDocuments: { label: 'Deleted or changed documents without justification', text: '{n} document(s) with a pending justification', none: 'No document with a pending justification' },
  unidentifiedChanges: { label: 'Changed records without a document', text: '{n} changed record(s) without a document', none: 'No changed record without a document' },
  inconsistentEntries: { label: 'Lines recorded as inconsistent', text: '{n} line(s) recorded as inconsistent: {pendentes} pending, {corrigidos} corrected', none: 'No line recorded as inconsistent' },
  noUserInclusions: { label: 'Lines inserted without a user in the log', text: '{n} line(s) inserted without a user in the log', none: 'No line inserted without a user in the log' },
  uncoveredDays: { label: 'Days of the period not covered by any extraction', text: '{n} day(s) of the period not covered by any extraction', none: 'Every day of the period is covered by an extraction' },
  daysWithoutEvents: { label: 'Business days of the period without any event', text: '{n} business day(s) without any event: {dias}', none: 'No business day without events' },
};

/** English field descriptions for the columns taken from kept fields. */
export const FIELD_LABELS_EN: Record<string, string> = {
  CT2_DATA: 'Accounting date',
  CT2_LOTE: 'Batch',
  CT2_SBLOTE: 'Sub-batch',
  CT2_DOC: 'Document number',
  CT2_LINHA: 'Line',
  CT2_MANUAL: 'Manual entry',
  CT2_VALOR: 'Amount',
  CT2_DEBITO: 'Debit account',
  CT2_CREDIT: 'Credit account',
  CT2_DC: 'Entry type',
  CT2_HIST: 'History',
  CT2_ROTINA: 'Routine',
  CT2_LP: 'Standard entry',
  CT2_ORIGEM: 'Source',
  CT2_INCONS: 'Inconsistency',
  CT2_TPSALD: 'Balance type',
  CT2_ESTCAN: 'Reversal',
  CT2_MOEDLC: 'Currency',
  CT2_CCD: 'Debit cost center',
  CT2_CCC: 'Credit cost center',
  CT2_ITEMD: 'Debit accounting item',
  CT2_ITEMC: 'Credit accounting item',
  CT2_USERGA: 'Record user/date',
};

export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, key: string) => (key in values ? String(values[key]) : m));
}
