/**
 * Test-only reader and formula evaluator for the workbooks generated by the tool. Supports the subset of
 * Excel used by the export: COUNTIFS, SUMIFS, SUM, SUMPRODUCT, ROUND, IF, IFERROR, ISNUMBER, INDEX, MATCH (exact),
 * AND, OR, NOT, LEN, TRIM, ABS, MAX, MIN, DATE, arithmetic, comparison and "&", ranges with sheet names and
 * defined names. Criteria strings follow Excel (">=46266", "<>Não identificado", "", "Manual").
 */
import { strFromU8, unzipSync } from 'fflate';

export type Value = number | string | boolean | null | Value[] | { error: string };
interface CellData {
  v: number | string | boolean | null;
  f?: string;
}

const dec = (s: string) =>
  s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/_x([0-9A-Fa-f]{4})_/g, (_, h: string) => String.fromCharCode(parseInt(h, 16)));

const colIndex = (s: string) => [...s].reduce((n, ch) => n * 26 + ch.charCodeAt(0) - 64, 0) - 1;
const isError = (v: Value): v is { error: string } => typeof v === 'object' && v !== null && !Array.isArray(v);

export class Workbook {
  readonly sheets = new Map<string, Map<string, CellData>>();
  readonly names = new Map<string, string>();
  private readonly memo = new Map<string, Value>();
  private readonly ranges = new Map<string, Value[]>();

  /** Reads the workbook; `only` limits the sheets parsed (large workbooks). */
  static async read(blob: Blob, only?: string[]): Promise<Workbook> {
    const files = unzipSync(new Uint8Array(await blob.arrayBuffer()));
    const text = (n: string) => strFromU8(files[n]!);
    const wb = new Workbook();
    const workbook = text('xl/workbook.xml');
    const sheetNames = [...workbook.matchAll(/<sheet name="([^"]+)" sheetId="(\d+)"/g)].map((m) => dec(m[1]!));
    for (const m of workbook.matchAll(/<definedName name="([^"]+)"[^>]*>([^<]+)<\/definedName>/g)) wb.names.set(m[1]!, dec(m[2]!));
    sheetNames.forEach((name, i) => {
      if (only && !only.includes(name)) return;
      const xml = text(`xl/worksheets/sheet${i + 1}.xml`);
      const cells = new Map<string, CellData>();
      for (const c of xml.matchAll(/<c r="([A-Z]+\d+)"([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)) {
        const attrs = c[2] ?? '';
        const body = c[3] ?? '';
        const f = /<f>([\s\S]*?)<\/f>/.exec(body)?.[1];
        const t = /t="(\w+)"/.exec(attrs)?.[1];
        let v: CellData['v'] = null;
        if (t === 'inlineStr') v = dec(/<t[^>]*>([\s\S]*?)<\/t>/.exec(body)?.[1] ?? '');
        else if (t === 'b') v = /<v>1<\/v>/.test(body);
        else {
          const raw = /<v>([^<]*)<\/v>/.exec(body)?.[1];
          if (raw !== undefined) v = Number(raw);
        }
        cells.set(c[1]!, { v, ...(f !== undefined && { f: dec(f) }) });
      }
      wb.sheets.set(name, cells);
    });
    return wb;
  }

  set(sheet: string, ref: string, v: CellData['v']): void {
    this.sheets.get(sheet)!.set(ref, { v });
    this.memo.clear();
    this.ranges.clear();
  }

  raw(sheet: string, ref: string): CellData | undefined {
    return this.sheets.get(sheet)?.get(ref);
  }

  /** Value of a cell, evaluating its formula. */
  value(sheet: string, ref: string): Value {
    const key = `${sheet}!${ref}`;
    const cached = this.memo.get(key);
    if (cached !== undefined) return cached;
    const cell = this.sheets.get(sheet)?.get(ref);
    let v: Value = null;
    if (cell?.f !== undefined) v = new Evaluator(this, sheet).evaluate(cell.f);
    else if (cell) v = cell.v;
    this.memo.set(key, v);
    return v;
  }

  range(sheet: string, from: string, to: string): Value[] {
    const key = `${sheet}!${from}:${to}`;
    const cached = this.ranges.get(key);
    if (cached) return cached;
    const a = /^([A-Z]+)(\d+)$/.exec(from)!;
    const b = /^([A-Z]+)(\d+)$/.exec(to)!;
    const out: Value[] = [];
    for (let r = Number(a[2]); r <= Number(b[2]); r++) {
      for (let c = colIndex(a[1]!); c <= colIndex(b[1]!); c++) {
        let name = '';
        let n = c + 1;
        while (n > 0) {
          const rem = (n - 1) % 26;
          name = String.fromCharCode(65 + rem) + name;
          n = Math.floor((n - 1) / 26);
        }
        out.push(this.value(sheet, `${name}${r}`));
      }
    }
    this.ranges.set(key, out);
    return out;
  }
}

type Token = { t: 'num' | 'str' | 'ref' | 'name' | 'op' | 'lp' | 'rp' | 'comma'; v: string };

function tokenize(src: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  while (i < src.length) {
    const ch = src[i]!;
    if (ch === ' ') {
      i++;
      continue;
    }
    if (ch === '"') {
      let s = '';
      i++;
      while (i < src.length) {
        if (src[i] === '"' && src[i + 1] === '"') {
          s += '"';
          i += 2;
        } else if (src[i] === '"') break;
        else s += src[i++];
      }
      i++;
      tokens.push({ t: 'str', v: s });
      continue;
    }
    const ref = /^(?:(?:'((?:[^']|'')+)'|([A-Za-z_][\w.]*))!)?\$?([A-Z]{1,3})\$?(\d+)(?::\$?([A-Z]{1,3})\$?(\d+))?/.exec(src.slice(i));
    if (ref && (ref[1] || ref[2] || !/^[A-Z]+\d*[(_]/.test(src.slice(i)))) {
      const sheet = ref[1]?.replace(/''/g, "'") ?? ref[2] ?? '';
      tokens.push({ t: 'ref', v: `${sheet}|${ref[3]}${ref[4]}|${ref[5] ? ref[5] + ref[6] : ''}` });
      i += ref[0].length;
      continue;
    }
    const num = /^\d+(\.\d+)?/.exec(src.slice(i));
    if (num) {
      tokens.push({ t: 'num', v: num[0] });
      i += num[0].length;
      continue;
    }
    const name = /^[A-Za-z_][\w.]*/.exec(src.slice(i));
    if (name) {
      tokens.push({ t: 'name', v: name[0] });
      i += name[0].length;
      continue;
    }
    const op = /^(<>|<=|>=|[-+*/&=<>])/.exec(src.slice(i));
    if (op) {
      tokens.push({ t: 'op', v: op[0] });
      i += op[0].length;
      continue;
    }
    if (ch === '(') tokens.push({ t: 'lp', v: ch });
    else if (ch === ')') tokens.push({ t: 'rp', v: ch });
    else if (ch === ',') tokens.push({ t: 'comma', v: ch });
    else throw new Error(`Token inesperado em "${src}": ${ch}`);
    i++;
  }
  return tokens;
}

const toNumber = (v: Value): number => {
  if (typeof v === 'number') return v;
  if (typeof v === 'boolean') return v ? 1 : 0;
  if (v === null || v === '') return 0;
  if (typeof v === 'string' && v.trim() !== '' && !Number.isNaN(Number(v))) return Number(v);
  return Number.NaN;
};
const toText = (v: Value): string => (v === null ? '' : typeof v === 'boolean' ? (v ? 'TRUE' : 'FALSE') : String(v));
const flat = (v: Value): Value[] => (Array.isArray(v) ? v : [v]);

function compare(a: Value, b: Value, op: string): boolean {
  let c: number;
  if (typeof a === 'string' || typeof b === 'string') {
    const x = toText(a).toLowerCase();
    const y = toText(b).toLowerCase();
    c = x < y ? -1 : x > y ? 1 : 0;
  } else c = toNumber(a) - toNumber(b);
  switch (op) {
    case '=': return c === 0;
    case '<>': return c !== 0;
    case '<': return c < 0;
    case '>': return c > 0;
    case '<=': return c <= 0;
    default: return c >= 0;
  }
}

/** COUNTIFS/SUMIFS criterion, compiled once per call. */
function matcher(criterion: Value): (cell: Value) => boolean {
  if (typeof criterion === 'number') return (cell) => typeof cell === 'number' && cell === criterion;
  const s = toText(criterion);
  const m = /^(<>|<=|>=|<|>|=)?(.*)$/s.exec(s)!;
  const op = m[1] ?? '=';
  const target = m[2]!;
  if (target === '') return op === '<>' ? (cell) => cell !== null && cell !== '' : (cell) => cell === null || cell === '';
  const n = Number(target);
  if (!Number.isNaN(n) && target.trim() !== '') return (cell) => (typeof cell !== 'number' ? op === '<>' : compare(cell, n, op));
  return (cell) => (cell === null ? op === '<>' : compare(toText(cell), target, op));
}

class Evaluator {
  private tokens: Token[] = [];
  private pos = 0;
  constructor(
    private readonly wb: Workbook,
    private readonly sheet: string,
  ) {}

  evaluate(formula: string): Value {
    this.tokens = tokenize(formula);
    this.pos = 0;
    try {
      return this.comparison();
    } catch (e) {
      return { error: (e as Error).message };
    }
  }

  private peek() {
    return this.tokens[this.pos];
  }
  private next() {
    return this.tokens[this.pos++]!;
  }

  private comparison(): Value {
    let left = this.concat();
    while (this.peek()?.t === 'op' && ['=', '<>', '<', '>', '<=', '>='].includes(this.peek()!.v)) {
      const op = this.next().v;
      const right = this.concat();
      left = this.binary(left, right, (a, b) => compare(a, b, op));
    }
    return left;
  }
  private concat(): Value {
    let left = this.additive();
    while (this.peek()?.v === '&') {
      this.next();
      const right = this.additive();
      left = this.binary(left, right, (a, b) => toText(a) + toText(b));
    }
    return left;
  }
  private additive(): Value {
    let left = this.term();
    while (this.peek()?.t === 'op' && (this.peek()!.v === '+' || this.peek()!.v === '-')) {
      const op = this.next().v;
      const right = this.term();
      left = this.binary(left, right, (a, b) => (op === '+' ? toNumber(a) + toNumber(b) : toNumber(a) - toNumber(b)));
    }
    return left;
  }
  private term(): Value {
    let left = this.unary();
    while (this.peek()?.t === 'op' && (this.peek()!.v === '*' || this.peek()!.v === '/')) {
      const op = this.next().v;
      const right = this.unary();
      left = this.binary(left, right, (a, b) => (op === '*' ? toNumber(a) * toNumber(b) : toNumber(a) / toNumber(b)));
    }
    return left;
  }
  private unary(): Value {
    if (this.peek()?.v === '-') {
      this.next();
      const v = this.unary();
      return Array.isArray(v) ? v.map((x) => -toNumber(x)) : -toNumber(v);
    }
    return this.primary();
  }
  private binary(a: Value, b: Value, fn: (x: Value, y: Value) => Value): Value {
    if (isError(a)) return a;
    if (isError(b)) return b;
    if (Array.isArray(a) || Array.isArray(b)) {
      const xs = flat(a);
      const ys = flat(b);
      const n = Math.max(xs.length, ys.length);
      return Array.from({ length: n }, (_, i) => fn(xs.length === 1 ? xs[0]! : xs[i]!, ys.length === 1 ? ys[0]! : ys[i]!));
    }
    return fn(a, b);
  }

  private reference(v: string): Value {
    const [sheet, from, to] = v.split('|');
    const s = sheet || this.sheet;
    return to ? this.wb.range(s, from!, to) : this.wb.value(s, from!);
  }

  private primary(): Value {
    const tok = this.next();
    if (tok.t === 'num') return Number(tok.v);
    if (tok.t === 'str') return tok.v;
    if (tok.t === 'ref') return this.reference(tok.v);
    if (tok.t === 'lp') {
      const v = this.comparison();
      this.next();
      return v;
    }
    if (tok.t === 'name') {
      if (this.peek()?.t === 'lp') {
        this.next();
        const args: (() => Value)[] = [];
        const starts: number[] = [];
        // Collect argument token ranges for lazy evaluation (IF, IFERROR).
        let depth = 0;
        let start = this.pos;
        if (this.peek()?.t !== 'rp') {
          while (this.pos < this.tokens.length) {
            const t = this.peek()!;
            if (t.t === 'lp') depth++;
            if (t.t === 'rp') {
              if (depth === 0) break;
              depth--;
            }
            if (t.t === 'comma' && depth === 0) {
              starts.push(start);
              args.push(this.lazy(start, this.pos));
              this.next();
              start = this.pos;
              continue;
            }
            this.next();
          }
          args.push(this.lazy(start, this.pos));
        }
        this.next(); // ")"
        return this.call(tok.v.toUpperCase(), args);
      }
      if (tok.v === 'TRUE') return true;
      if (tok.v === 'FALSE') return false;
      const def = this.wb.names.get(tok.v);
      if (!def) return { error: `nome ${tok.v}` };
      return new Evaluator(this.wb, this.sheet).evaluate(def);
    }
    throw new Error(`token ${tok.v}`);
  }

  private lazy(from: number, to: number): () => Value {
    const slice = this.tokens.slice(from, to);
    return () => {
      const e = new Evaluator(this.wb, this.sheet);
      (e as unknown as { tokens: Token[] }).tokens = slice;
      return e.comparison();
    };
  }

  private call(name: string, args: (() => Value)[]): Value {
    const a = (i: number) => args[i]!();
    switch (name) {
      case 'IF': {
        const c = a(0);
        return (typeof c === 'boolean' ? c : toNumber(c) !== 0) ? a(1) : args[2] ? a(2) : false;
      }
      case 'IFERROR': {
        const v = a(0);
        return isError(v) || (typeof v === 'number' && Number.isNaN(v)) ? a(1) : v;
      }
      case 'ISNUMBER': {
        const v = a(0);
        return typeof v === 'number' && Number.isFinite(v);
      }
      case 'AND': return args.every((_, i) => { const v = a(i); return typeof v === 'boolean' ? v : toNumber(v) !== 0; });
      case 'OR': return args.some((_, i) => { const v = a(i); return typeof v === 'boolean' ? v : toNumber(v) !== 0; });
      case 'NOT': { const v = a(0); return !(typeof v === 'boolean' ? v : toNumber(v) !== 0); }
      case 'LEN': return toText(a(0)).length;
      case 'TRIM': return toText(a(0)).trim().replace(/\s+/g, ' ');
      case 'ABS': return Math.abs(toNumber(a(0)));
      case 'ROUND': { const f = 10 ** toNumber(a(1)); return Math.round(toNumber(a(0)) * f + Number.EPSILON) / f; }
      case 'DATE': return 0; // not needed for values in the tests
      case 'SUM': return args.reduce((n, _, i) => n + flat(a(i)).reduce<number>((m, x) => m + (typeof x === 'number' ? x : 0), 0), 0);
      case 'MAX': return Math.max(...args.flatMap((_, i) => flat(a(i)).filter((x): x is number => typeof x === 'number')));
      case 'MIN': return Math.min(...args.flatMap((_, i) => flat(a(i)).filter((x): x is number => typeof x === 'number')));
      case 'SUMPRODUCT': {
        const arrays = args.map((_, i) => flat(a(i)).map(toNumber));
        return arrays[0]!.reduce((n, _, k) => n + arrays.reduce((p, arr) => p * (arr[k] ?? 0), 1), 0);
      }
      case 'INDEX': {
        const range = flat(a(0));
        const i = toNumber(a(1));
        if (!(i >= 1 && i <= range.length)) return { error: '#REF!' };
        return range[i - 1]!;
      }
      case 'MATCH': {
        const target = a(0);
        const range = flat(a(1));
        const i = range.findIndex((x) => x !== null && compare(x, target, '='));
        return i < 0 ? { error: '#N/A' } : i + 1;
      }
      case 'COUNTIFS':
      case 'SUMIFS': {
        const offset = name === 'SUMIFS' ? 1 : 0;
        const sumRange = offset ? flat(a(0)) : null;
        const pairs: [Value[], (cell: Value) => boolean][] = [];
        for (let i = offset; i < args.length; i += 2) pairs.push([flat(a(i)), matcher(a(i + 1))]);
        let total = 0;
        const n = pairs[0]![0].length;
        for (let k = 0; k < n; k++) {
          if (pairs.every(([range, test]) => test(range[k] ?? null))) total += sumRange ? toNumber(sumRange[k] ?? 0) || 0 : 1;
        }
        return total;
      }
      default:
        return { error: `função ${name}` };
    }
  }
}
